/*
 * PharmaTrace Supply Chain Information Network API
 * The PharmaTrace SCIN API provides network members a resource and process oriented access to the blockchain backed market and inventory information. It represents a layer of abstraction above the Hyperledger network to facilitate a business focused development of clients and integration systems without the need to directly connect to Hyperledger nodes.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: api@pharmatrace.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.pharmatrace.api.scin.pub.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Stakeholder
 */
public class StakeholderTest {
    private final Stakeholder model = new Stakeholder();

    /**
     * Model tests for Stakeholder
     */
    @Test
    public void testStakeholder() {
        // TODO: test Stakeholder
    }

    /**
     * Test the property 'tradeId'
     */
    @Test
    public void tradeIdTest() {
        // TODO: test tradeId
    }

    /**
     * Test the property 'tradeIdType'
     */
    @Test
    public void tradeIdTypeTest() {
        // TODO: test tradeIdType
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    public void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'stakeholderRole'
     */
    @Test
    public void stakeholderRoleTest() {
        // TODO: test stakeholderRole
    }

    /**
     * Test the property 'walletId'
     */
    @Test
    public void walletIdTest() {
        // TODO: test walletId
    }

}
